# -*- coding: utf-8 -*-
"""Bus.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ONtljv2WcAprPD6dj9Zoc348vAaKfcfv
"""

import numpy as np

bus = np.empty((10,4), dtype=object)

asiento = 0
for i in range(10):
  for j in range(4):
    asiento = asiento + 1
    bus[i,j]=asiento

print(bus)

nro_asiento = int(input("Elija el número de asiento a comprar "))

result = np.where(bus==nro_asiento)
bus[result] = 'X'

print(bus)

import numpy as np

bus = np.empty((10,5), dtype=object)

asiento = 0
for i in range(10):
  for j in range(5):
    if j == 2:
      bus[i,j]= ' '
    else:
      asiento = asiento + 1
      bus[i,j]=asiento

print(bus)

nro_asiento = int(input("Elija el número de asiento a comprar "))

result = np.where(bus==nro_asiento)
bus[result] = 'X'

print(bus)