# -*- coding: utf-8 -*-
"""clase de arreglos unidimensionales.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XnajKvPeDmtnvW-XPwwTszQ75hBj4Nkf
"""

import numpy as np
arreglo = np.array([1,2,3,4])
#print(arreglo)
arreglo

#ndim
arreglo.ndim

#largo
len(arreglo)

# estructura dim
arreglo.shape

# intervalos
arreglo[0:3] #intervalo desde primer número hasta el segundo sin considerar el segundo
arreglo[0:3:2] #intervalo 0 al 3 y va tomando las posiciones 2 (incluye el primero)
arreglo[::3] #de todos los elementos del arreglo va tomando las posiciones 3 (incluye el primero)
arreglo[2::1] #desde la posicion 2 hasta el final moviendonos de a 1

# encontrar valor de atrás hacia adelante
arreglo[-4]

# lista creada con un rango de 0 hasta 5 sin considerar el ultimo
c = [i for i in range(0,5)]

# misma lista creada con un rango de 0 hasta 5 sin considerar el ultimo, pero de 2 en 2
a = []
for i in range(0,5,2):
  a.append(i)

#print(c)
#print(a)

#for i in range(len(arreglo)): #devuelve los indices que tiene el arreglo
#  print(arreglo[i])

#for i in arreglo: #devuelve los valores que tiene el arreglo
#  print(i)

# crear arreglo con enteros en un rango de 0 a 7
arreglo2 = np.arange(7)
arreglo2

# crear arreglo con decimales en un rango de 0 a 5 
arreglo3 = np.arange(5.0)
arreglo3

# crear arreglo con enteros en un rango de 2 a 7
arreglo4 = np.arange(2,7)
arreglo4

# crear arreglo con enteros en un rango de 2 a 8 pero de 3 en 3
arreglo4 = np.arange(2,8,3)
arreglo4

# el espejo de 2 arreglos
arregloX = np.array([4,7,5,10,8,33])
#print(arregloX)
arregloY = arregloX
#print(arregloY)
arregloX[0] = 100
#print(arregloX)
#print(arregloY)

# el copiado de arreglos
arregloZ = np.array([4,7,5,10,8,33])
#print(arregloZ)
arregloW = arregloZ.copy()
#print(arregloW)
arregloZ[0] = 100
#print(arregloZ)
#print(arregloW)

arregloO = np.array([4,7,5,10,8,33])
#print(arregloO)
#print(arregloO+1) #suma
#print(arregloO*2) #multiplicacion
#print(arregloO**2) #exponencial

# operaciones 2 arreglos
array1 = np.ones(7, dtype=np.int32)
array2 = np.array([8,7,9,20,43,39,1])
#print(array1)
#print(array2)
#print(array1+array2)#suma
#print(array1*array2)#multiplicacion
#print(array1==array2)#comparación
#print(array1<array2)#mayor que

# funciones de un arreglo
#print(array2.sum())
#print(array2.mean())
#print(array2.min())
#print(array2.max())

arregloA = np.random.randint(100, size=10)
print(arregloA)
arregloB = arregloA.copy()
print(arregloB)

print(arregloB.max())
print(arregloB.min())
print(arregloB.sum())
print(arregloB.mean())