# -*- coding: utf-8 -*-
"""resolución a desafio en clases.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15eucVoGtKtKLSBNzilkFY-NsAOCCvZWd
"""

import numpy as np

# crear arreglo A de 100 elementos con números al azar de 0 a 500
arregloA = np.random.randint(500, size=100)
print(arregloA)

# Mostrar por pantalla sólo los valores que se encuentren en los índices pares del arreglo.
print(arregloA[2::2])

#Mostrar el elemento mayor del arreglo.
print(arregloA.max())

#Mostrar el índice (posición) del elemento mayor.
print(np.where(arregloA == arregloA.max())[0])

#Mostrar el elemento menor del arreglo.
print(arregloA.min())

#Generar la copia de arreglo A a un arreglo B y multiplicar por 3 cada elemento. Mostrar resultado.
arregloB = arregloA.copy() * 3
print(arregloB)

#Mostrar la suma de los elementos del segundo arreglo.
print(arregloB.sum())

#Calcular el promedio de los elementos del segundo arreglo.
print(arregloB.mean())

#Contar los elementos pares del segundo arreglo.
print(len(arregloB[arregloB%2==0]))
print(np.count_nonzero(arregloB%2==0))

#Sumar los elementos impares del segundo arreglo.
print(arregloB[arregloB%2!=0].sum())

#Emitir mensaje por cada elemento primo de primer arreglo
for num in arregloB:
  primo = True
  if num > 1:
    for i in range(2,num):
      if num%i==0:
        primo = False
    if primo:
      print(f"numero {num} es primo")